# Generated by Django 3.2.23 on 2024-01-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_members',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
