# Generated by Django 3.2.23 on 2024-01-06 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_club_members_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_pass',
            name='DEPARTMENT',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AddField(
            model_name='bus_pass',
            name='academic_year',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='bus_pass',
            name='f_place',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='bus_pass',
            name='to_place',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
