# Generated by Django 3.2.23 on 2024-01-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240106_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_card',
            name='STUDENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
            preserve_default=False,
        ),
    ]
