# Generated by Django 3.2.23 on 2024-01-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_id_card_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_card',
            name='STUDENT',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
