# Generated by Django 3.2.23 on 2024-01-06 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_id_card_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_card',
            name='STUDENT',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
