# Generated by Django 3.2.23 on 2024-01-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_id_card_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_card',
            name='DEPARTMENT',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AddField(
            model_name='id_card',
            name='academic_year',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
