# Generated by Django 3.2.23 on 2024-01-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20240107_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id_card',
            name='student_name',
        ),
    ]
