# Generated by Django 3.2.23 on 2024-01-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_id_card_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id_card',
            name='register_number',
        ),
    ]
