# Generated by Django 3.2.23 on 2024-03-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_id_card_register_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujectallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.subject')),
                ('TEACHERS', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.teachers')),
            ],
        ),
    ]
