# Generated by Django 3.2.23 on 2024-03-07 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_sujectallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='COURSE',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
