# Generated by Django 3.2.23 on 2024-03-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20240307_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.AddField(
            model_name='attendance',
            name='SUJECTALLOCATION',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.sujectallocation'),
        ),
    ]
