# Generated by Django 3.2.23 on 2024-03-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20240308_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='COURSE',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sem',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
