# Generated by Django 3.2.23 on 2024-03-08 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20240308_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='day',
            new_name='hour',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='SUJECTALLOCATION',
        ),
        migrations.AddField(
            model_name='attendance',
            name='SUBJECT',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='absent', max_length=100),
        ),
    ]
