# Generated by Django 3.2.23 on 2024-03-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notification', models.CharField(max_length=100)),
                ('TEACHERS', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Notification_office_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notification', models.CharField(max_length=100)),
                ('OFFICE_STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.office_staff')),
            ],
        ),
        migrations.CreateModel(
            name='Notification_club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notification', models.CharField(max_length=100)),
                ('CLUB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.club')),
            ],
        ),
    ]
